name: Fastlane Match (Create Certs Once)

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Git identity
        run: |
          git config --global user.email "ci-bot@example.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MATCH_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global url."git@github.com:".insteadOf "https://github.com/"

      - name: Install Ruby & Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - run: gem install fastlane -N

      - name: Run Match in create mode
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          fastlane match appstore \
            --api_key_path api_key.json \
            --git_branch main \
            --readonly false \
            --force true \
            --generate_apple_certs true \
            --verbose
