name: Generate App Store Certificate (One-Time)

on:
  workflow_dispatch:

jobs:
  generate-appstore-cert:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Fastlane
        run: sudo gem install fastlane -N

      - name: Create api_key.json
        run: printf "%s" "${{ secrets.APP_STORE_CONNECT_API_KEY }}" > api_key.json

      - name: DEBUG â€” Print API key content
        run: |
          echo "===== SECRET CONTENT START ====="
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}"
          echo "===== SECRET CONTENT END ====="


      - name: Setup SSH for Match Repo
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MATCH_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Generate App Store Certificate
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          fastlane match appstore \
            --verbose \
            --force \
            --api_key_path api_key.json \
            --git_branch main
