name: Fastlane Match (Readonly)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  match:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- SSH SETUP FOR MATCH REPO ---
      - name: Setup SSH for Match Repo
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MATCH_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global url."git@github.com:".insteadOf "https://github.com/"

      # Install Ruby & Fastlane
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Fastlane
        run: gem install fastlane -N

      # Create API key file for App Store Connect
      - name: Create api_key.json
        run: printf "%s" "${{ secrets.APP_STORE_CONNECT_API_KEY }}" > api_key.json

      # Debugging â€“ show files
      - name: List project files
        run: ls -R .
        
      - name: Run Fastlane Match (Create or Update Certificates)
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          fastlane match appstore \
            --verbose \
            --api_key_path api_key.json \
            --git_branch main \
            --readonly false \
            --force \
            --generate_apple_certs true
