name: Fastlane Match (Readonly)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  match:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Ruby & Fastlane
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Fastlane
        run: gem install fastlane -N

      # Create API key file for App Store Connect
      - name: Create api_key.json
        run: echo "${{ secrets.APP_STORE_CONNECT_API_KEY}}" > api_key.json

      # Debugging â€“ show files
      - name: List project files
        run: ls -R .

      # Run Match (App Store only)
      - name: Run Fastlane Match (Readonly)
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          fastlane match appstore \
            --readonly \
            --verbose \
            --api_key_path api_key.json \
            --git_branch master
