name: Fastlane Match (Readonly)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  match:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git Identity
        run: |
          git config --global user.email "ci-bot@example.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Setup SSH for Match Repo
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MATCH_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global url."git@github.com:".insteadOf "https://github.com/"

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Fastlane
        run: gem install fastlane -N

      - name: Run Fastlane Match (READ EXISTING CERTS ONLY)
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          fastlane match appstore \
            --api_key_path api_key.json \
            --git_branch main \
            --readonly true
